### ISSUE TITLE
Issue - `exec /bin/sh: exec format error`

### ISSUE THREAD

**Issue by kaumudpa** [nexryai/camera.ui-docker#1]
The image does not run this is the error from the container's logs.

`exec /bin/sh: exec format error`
My device is Raspberry Pi 4b 8GB
Ubuntu

**Comment by kaumudpa** [comment]
The issue is - `docker no matching manifest for linux/arm64/v8 in the manifest list entries`

**Comment by nexryai** [comment]
I tried arm64 support, but the [build fails midway](https://github.com/nexryai/camera.ui-docker/actions/runs/6129509469/job/16637674060#step:6:270)


This may be related to [camera.ui/issues/416](https://github.com/seydx/camera.ui/issues/416)

**Comment by kaumudpa** [comment]
Nopes. I got it running on my pi without any issues via rpm.

Issue is specific to this docker image.

**Comment by nexryai** [comment]
I was careless...
I missed the "You need to install the latest version of Python." output in the Action log.
I added the missing packages and the build succeeded.
Please try to see if `:alpine` tag image works on your raspberry pi.

**Comment by kaumudpa** [comment]
Yes its working now!

Thank you.
